import type { Metadata } from "next";
import { Raleway } from "next/font/google";

// styles
import "@/styles/main.scss";

// components
import StoreProvider from "@/lib/redux/provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const raleway = Raleway({
    subsets: ["latin"],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={raleway.className}>
            <body>
                <StoreProvider>{children}</StoreProvider>
            </body>
        </html>
    );
}
